displayName=Moonlight Antelope Hunting
author=Proddy
description=A plugin to provide useful overlays for moonlight antelope hunting
tags=moonlight,antelope,hunting,fur
version=1.0
plugins=org.zhbot.moonlight_antelop_hunting.MoonlightAntelopeHuntingPlugin
build=standard